// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzETeB543xrVQ307sqw0C0xZyYJOffFeM',
    appId: '1:220803345979:web:77a745ffacbe0a3a6f361e',
    messagingSenderId: '220803345979',
    projectId: 'app-e-ecommerce',
    authDomain: 'app-e-ecommerce.firebaseapp.com',
    storageBucket: 'app-e-ecommerce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDPDS8hXQNfkH7bhGzO1JH7vgLY8jv29Q',
    appId: '1:220803345979:android:912879f3dcad94da6f361e',
    messagingSenderId: '220803345979',
    projectId: 'app-e-ecommerce',
    storageBucket: 'app-e-ecommerce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRDPf2R0o-X9cYTn2NyojMX6ktNq9yLZc',
    appId: '1:220803345979:ios:f8d261f9ed7f4ead6f361e',
    messagingSenderId: '220803345979',
    projectId: 'app-e-ecommerce',
    storageBucket: 'app-e-ecommerce.appspot.com',
    iosBundleId: 'com.example.appEEcommerce',
  );
}
